"""pb_invoice — Generate PDF invoices from structured data."""

import uuid
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from protocolbox.server import mcp


@mcp.tool()
def generate_invoice(data: dict[str, Any]) -> str:
    """Generate a PDF invoice from structured data.

    The data dict must contain at minimum:
        - client_name (str): Name of the client.
        - total (float | int): Invoice total amount.

    Optional fields:
        - invoice_number (str): Custom invoice number.
        - items (list[dict]): Line items with 'description', 'qty', 'price'.
        - currency (str): Currency symbol (default: "$").
        - notes (str): Additional notes for the invoice.

    Args:
        data: Dictionary containing invoice details.

    Returns:
        The file path to the generated PDF, or an error message.
    """
    # --- Validate required fields ---
    client_name = data.get("client_name")
    total = data.get("total")

    if not client_name:
        return "Error: 'client_name' is required in the data dict."
    if total is None:
        return "Error: 'total' is required in the data dict."

    try:
        total = float(total)
    except (TypeError, ValueError):
        return "Error: 'total' must be a number."

    # --- Set up defaults ---
    invoice_number = data.get("invoice_number", f"INV-{uuid.uuid4().hex[:8].upper()}")
    currency = data.get("currency", "$")
    items: list[dict[str, Any]] = data.get("items", [])
    notes: str = data.get("notes", "")

    # --- Generate PDF ---
    file_path = f"/tmp/invoice_{uuid.uuid4().hex}.pdf"
    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 24)
    c.drawString(30 * mm, height - 30 * mm, "INVOICE")

    c.setFont("Helvetica", 10)
    c.drawString(30 * mm, height - 40 * mm, f"Invoice #: {invoice_number}")

    # Client info
    c.setFont("Helvetica-Bold", 12)
    c.drawString(30 * mm, height - 55 * mm, "Bill To:")
    c.setFont("Helvetica", 11)
    c.drawString(30 * mm, height - 62 * mm, str(client_name))

    # Line items
    y_pos = height - 80 * mm

    if items:
        # Table header
        c.setFont("Helvetica-Bold", 10)
        c.drawString(30 * mm, y_pos, "Description")
        c.drawString(120 * mm, y_pos, "Qty")
        c.drawString(145 * mm, y_pos, "Price")
        c.drawString(170 * mm, y_pos, "Subtotal")
        y_pos -= 7 * mm

        # Draw a line
        c.line(30 * mm, y_pos + 3 * mm, 190 * mm, y_pos + 3 * mm)

        c.setFont("Helvetica", 10)
        for item in items:
            desc = str(item.get("description", "—"))
            qty = item.get("qty", 1)
            price = item.get("price", 0)
            subtotal = float(qty) * float(price)

            c.drawString(30 * mm, y_pos, desc[:40])
            c.drawString(120 * mm, y_pos, str(qty))
            c.drawString(145 * mm, y_pos, f"{currency}{price:.2f}")
            c.drawString(170 * mm, y_pos, f"{currency}{subtotal:.2f}")
            y_pos -= 6 * mm

        y_pos -= 5 * mm

    # Total
    c.line(30 * mm, y_pos + 3 * mm, 190 * mm, y_pos + 3 * mm)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(145 * mm, y_pos - 5 * mm, f"Total: {currency}{total:.2f}")
    y_pos -= 20 * mm

    # Notes
    if notes:
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(30 * mm, y_pos, f"Notes: {notes}")

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(30 * mm, 15 * mm, "Generated by ProtocolBox — protocolbox.in")

    c.save()

    return file_path


def _validate_invoice_data(data: dict[str, Any]) -> str | None:
    """Validate invoice data, returning an error message or None."""
    if not isinstance(data, dict):
        return "Error: Input must be a dictionary."
    if "client_name" not in data:
        return "Error: 'client_name' is required."
    if "total" not in data:
        return "Error: 'total' is required."
    return None
